services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    env_file: ./.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - net_wordpress_mariadb
    expose:
      - ${MARIADB_PORT_INTERNAL:-3306}
    secrets:
      - mariadb_user
      - mariadb_user_password
      - mariadb_root_password
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    env_file: ./.env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_mariadb
      - nginx_wordpress
    expose:
      - ${WORDPRESS_PORT_INTERNAL:-9000}
    secrets:
      - wordpress_user
      - wordpress_user_password
      - wordpress_user_email
      - worspress_admin
      - wordpress_admin_password
      - wordpress_admin_email
    restart: unless-stopped

  ngingx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    env_file: ./.env
    depends_on:
      - wordpress
    networks:
      - nginx_wordpress
    ports:
      - "${NGINX_PORT_HOST:-443}:${NGINX_PORT_INTERNAL:-443}"
    restart: unless-stopped

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  wordpress_mariadb:
    driver: bridge
  nxinx_wordpress:
    driver: bridge

secrets:
  mariadb_user:
    file: ${MARIADB_USER_FILE}
  mariadb_user_password:
    file: ${MARIADB_USER_PASSWORD_FILE}
  mariadb_root_password:
    file: ${MARIADB_ROOT_PASSWORD_FILE}
  wordpress_user:
    file: ${WORDPRESS_USER_FILE}
  wordpress_user_password:
    file: ${WORDPRESS_USER_PASSWORD_FILE}
  wordpress_user_email:
    file: ${WORDPRESS_USER_EMAIL_FILE}
  wordpress_admin:
    file: ${WORDPRESS_ADMIN_FILE}
  wordpress_admin_password:
    file: ${WORDPRESS_ADMIN_PASSWORD_FILE}
  wordpress_admin_email:
    file: ${WORDPRESS_ADMIN_EMAIL_FILE}
