services:
  mariadb:
    container_name: ${DATABASE_HOSTNAME:-mariadb}
    build:
      context: ./requirements/mariadb
      args:
        MYSQL_TCP_PORT: ${MARIADB_PORT_INTERNAL:-3306}
    image: mariadb:inception
    pull_policy: build
    env_file: ./.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wordpress_mariadb
    expose:
      - ${MARIADB_PORT_INTERNAL:-3306}
    secrets:
      - mariadb_user
      - mariadb_user_password
      - mariadb_root_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--host=localhost", "--protocol=tcp"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

  wordpress:
    container_name: ${FRONTEND_HOSTNAME:-wordpress}
    build:
      context: ./requirements/wordpress
      args:
        WORDPRESS_PORT_INTERNAL: ${WORDPRESS_PORT_INTERNAL:-9000}
    image: wordpress:inception
    pull_policy: build
    env_file: ./.env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/app
    networks:
      - wordpress_mariadb
      - nginx_wordpress
    expose:
      - ${WORDPRESS_PORT_INTERNAL:-9000}
    secrets:
      - wordpress_user
      - wordpress_user_email
      - wordpress_user_password
      - wordpress_admin
      - wordpress_admin_email
      - wordpress_admin_password
      - mariadb_user
      - mariadb_user_password
    restart: unless-stopped

  ngingx:
    container_name: ${SERVER_HOSTNAME:-nginx}
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
        NGINX_PORT_INTERNAL: ${NGINX_PORT_INTERNAL:-443}
        WORDPRESS_PORT_INTERNAL: ${WORDPRESS_PORT_INTERNAL:-9000}
    image: nginx:inception
    pull_policy: build
    env_file: ./.env
    depends_on:
      - wordpress
    networks:
      - nginx_wordpress
    ports:
      - "${NGINX_PORT_HOST:-443}:${NGINX_PORT_INTERNAL:-443}"
    restart: unless-stopped

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  wordpress_mariadb:
    driver: bridge
  nginx_wordpress:
    driver: bridge

secrets:
  mariadb_user:
    file: ${MARIADB_USER_FILE}
  mariadb_user_password:
    file: ${MARIADB_USER_PASSWORD_FILE}
  mariadb_root_password:
    file: ${MARIADB_ROOT_PASSWORD_FILE}
  wordpress_user:
    file: ${WORDPRESS_USER_FILE}
  wordpress_user_password:
    file: ${WORDPRESS_USER_PASSWORD_FILE}
  wordpress_user_email:
    file: ${WORDPRESS_USER_EMAIL_FILE}
  wordpress_admin:
    file: ${WORDPRESS_ADMIN_FILE}
  wordpress_admin_password:
    file: ${WORDPRESS_ADMIN_PASSWORD_FILE}
  wordpress_admin_email:
    file: ${WORDPRESS_ADMIN_EMAIL_FILE}
