FROM debian:stable

WORKDIR /usr/src/app

EXPOSE 5000

RUN apt-get update && apt-get install curl -y
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get install nodejs -y
COPY . .
RUN npm install
RUN npm run build
RUN npm install -g serve

CMD ["-s", "-l", "5000", "build"]
ENTRYPOINT ["serve"]
